import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { CreatorCard, MainLayout } from "../components";
import { client } from "../lib/graphcms-client";
import { CREATORS } from "../lib/queries";
import type { Creator } from "../types";

type Props = {
  creators: Creator[];
};

export const getStaticProps: GetStaticProps = async () => {
  const data = await client.request(CREATORS);

  return {
    props: {
      creators: data.creators as Creator[],
    },
  };
};

const Home: NextPage<Props> = ({ creators }) => {
  return (
    <div>
      <Head>
        <title>Creators App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <h1 className="text-4xl font-bold">Creators</h1>

        <div className="mt-8 grid sm:grid-cols-2 md:grid-cols-3 gap-8">
          {creators.map((creator) => (
            <CreatorCard key={creator.id} creator={creator} />
          ))}
        </div>
      </MainLayout>
    </div>
  );
};

export default Home;
